### ISSUE TITLE
Incompatible with Python 3

### ISSUE THREAD

**Issue by jpgill86** [CWRUChielLab/axographio#1]
axographio v0.1.1b1 and earlier is incompatible with Python 3. Installation fails with an error:

```
$ pip3 install axographio==0.1.1b1
Downloading/unpacking axographio==0.1.1b1
  Downloading axographio-0.1.1b1.tar.gz (77kB): 77kB downloaded
  Running setup.py (path:/tmp/pip_build_gill/axographio/setup.py) egg_info for package axographio
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_gill/axographio/setup.py", line 13, in <module>
        m.Extension.__dict__ = m._Extension.__dict__
    AttributeError: attribute '__dict__' of 'type' objects is not writable
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_gill/axographio/setup.py", line 13, in <module>

    m.Extension.__dict__ = m._Extension.__dict__

AttributeError: attribute '__dict__' of 'type' objects is not writable
```

**Comment by jpgill86** [comment]
Fixed by #2
